name: Build firmware
on:
  push:
    paths:
      - config/**
      - zephyr/**
      - build.yaml
      - .github/workflows/build.yml
  workflow_dispatch:
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
